spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/postgresql
    baseline-on-migrate: true
    validate-on-migrate: false
    placeholders:
      library-file-hashing: "true"
      library-scan-startup: "false"
      delete-empty-collections: "true"
      delete-empty-read-lists: "true"

  jpa:
    hibernate:
      ddl-auto: validate

  jooq:
    sql-dialect: postgres

komga:
  database:
    type: POSTGRESQL
    url: jdbc:postgresql://localhost:5433/komga
    username: komga
    password: komga123
    pool-size: 10
    max-pool-size: 10
  tasks-db:
    type: POSTGRESQL
    url: jdbc:postgresql://localhost:5433/komga_tasks
    username: komga
    password: komga123
    pool-size: 25
    max-pool-size: 25

server:
  port: 25601

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc: DEBUG
