CREATE INDEX IF NOT EXISTS idx_task_queue
  ON "TASK" ("OWNER", "PRIORITY" DESC, "LAST_MODIFIED_DATE")
  WHERE "OWNER" IS NULL;

CREATE INDEX IF NOT EXISTS idx_task_owner_group
  ON "TASK" ("OWNER", "GROUP_ID")
  WHERE "OWNER" IS NOT NULL AND "GROUP_ID" IS NOT NULL;
