application.version: 1.0

komga:
  database:
    file: /tmp/komga/database.sqlite
  config-dir: /tmp/komga
  tasks-db:
    file: /tmp/komga/tasks.sqlite

spring:
  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
    mixed: true
    placeholders:
      library-file-hashing: true
      library-scan-startup: false
      delete-empty-collections: true
      delete-empty-read-lists: true

server:
  port: 25600

logging:
  level:
    org.gotson.komga: INFO